export interface Effect {
    effectType: EffectType;
    value?: number;
}
export type EffectType = 'BUDGET' | 'KNOWLEDGE' | 'CREATIVITY' | 'ORGANIZATION' | 'PRESTIGE'
    | 'DISMISS' | 'PURGE_CONTRACT' | 'PURGE_PERSON' | 'PURGE_ITEM' | 'DRAW'| 'DRAW_UNTIL_PERSON'
    | 'BUY_TO_DECK' | 'BUY_FROM_TRASH' | 'SCOUT_CONTRACTS'|'FIRST_RECRUITMENT_DISCOUNT'
    | 'ENTERTAINMENT_BONUS_SP' | 'MANUFACTURING_BONUS_SP' | 'HEALTHCARE_BONUS_SP'
    | 'ENTERTAINMENT_SKILL_BONUS' | 'MANUFACTURING_SKILL_BONUS' | 'HEALTHCARE_SKILL_BONUS'
    | 'TRAINING' | 'SUPPORT';
